### ISSUE TITLE
Modul Trouble

### ISSUE THREAD

**Issue by ghost** [masterperson40/ewaste3Dprinter#1]
The Makro (makePrinter.py) starts working but stops with an error.

bash says:

---

bash $ python makePrinter.py
FreeCAD 0.15, Libs: 0.15R4671 (Git)
Traceback (most recent call last):
  File "makePrinter.py", line 539, in <module>
    uf.makeAssemblyFile()
  File "/home/home/stahlstngel/Arbeitsfläche/3D-Printer/master/utilityFunctions.py", line 315, in makeAssemblyFile
    Gui.ActiveDocument=Gui.getDocument("PrinterAssembly")
AttributeError: 'module' object has no attribute 'getDocument'

---

Thats the same mit every Gui.getDocument -cmd.

Can somebody help?

**Comment by biosafetylvl5** [comment]
It seems like you are trying to run makePrinter.py directly from the command line. While we intend to add this functionality in the future, FreeCAD has some development that needs to happen before we can do so. Right now one must run "makePrinter.py" through the FreeCAD macro interface, as show in the readme's ["Test" section](https://github.com/masterperson40/ewaste3Dprinter#tests). Let me know if this solves your problem.

**Comment by ghost** [comment]
I know and i did it that way. But the errors in FreeCAD are temporary and disappear after a few seconds.
So yes.....i tried the command line to find the problem and there are the same errors like in FreeCAD.

After executing the makro in FreeCAD the first 2 rods are created and then it stops by xCarriage1.

**Comment by biosafetylvl5** [comment]
To view errors in FreeCAD, go to View > Views > Report View, and enable "Report View". After doing so, could you post the error message? Moreover, what operating system and python version are you using?

**Comment by ghost** [comment]
ok....in deed there are a bit different:

FreeCAD:

---

Traceback (most recent call last):
  File "/home/stahlstngel/Arbeitsfläche/3D-Printer/master/makePrinter.py", line 548, in <module>
    xCarriage.draw()
  File "/home/stahlstngel/Arbeitsfläche/3D-Printer/master/xCarriage.py", line 1033, in draw
    None, None)#(App.ActiveDocument.Pad004,["Face43"])
  File "/home/stahlstngel/Arbeitsfläche/3D-Printer/master/utilityFunctions.py", line 92, in getFace
    raise Exception("getFace() error: No such face exists.")
<type 'exceptions.Exception'>: getFace() error: No such face exists.

---

**Comment by biosafetylvl5** [comment]
What operating system are using? And, what version of FreeCAD and python are you using?

**Comment by ghost** [comment]
bash $ uname -a
Linux AMDquad 3.16.0-38-generic #52~14.04.1-Ubuntu SMP Fri May 8 09:43:57 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

bash $ cat /etc/issue
Linux Mint 17.2 Rafaela \n \l

bash $ freecad -v
FreeCAD 0.15 Revision: 4671 (Git)

bash $ python -V
Python 2.7.6

But there is also:
python            python2.7         python2-config    python3.4         python3m
python2           python2.7-config  python3           python3.4m        python-config
and i dont no which python is used.

**Comment by biosafetylvl5** [comment]
Try using Ubuntu's specific (FreeCAD packages](http://packages.ubuntu.com/freecad). We have been developing on FreeCAD .14 Revision 2935 (Git) which is the highest version of FreeCAD that is stable for Debian based Linux distributions. While a downgrade may be a temporary fix, we will look into the problem further, and will get it working.

**Comment by biosafetylvl5** [comment]
Running "sudo apt-get install freecad=0.13.2935-dfsg-1.1build1" should downgrade you to the older version of FreeCAD. If your problems persist, please let us know. Moreover, thank you for bring this incompatibility with the new version of FreeCAD to our attention.

**Comment by ghost** [comment]
Great work.

Now it works fantastic. Thanks a lot and have a nice night.

**Comment by Maaphoo** [comment]
Hi stahlstngel, Thanks for reporting this one. I've been working away on similar geometry problems for a while. It all springs from the numbering of the faces and edges of a part being different when the macros are run on different computers. I created the getFace() and getEdge() functions to solve this problem but sometimes it still rears its head. I'll play around with it a bit and see if I can locate where the failure is.
